# .env
spring.config.import=optional:file:.env.dev[.properties]
# Port
server.port=${PORT:8080}
# DataSource
spring.datasource.url=jdbc:postgresql://${DB_URL}:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#jdbc:postgresql로 인해 자동으로 로딩 처리 됨
# JPA/Hibernate
# DDL (create X, update or validate)
spring.jpa.hibernate.ddl-auto=update
# SQL 로그로 확인
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true